// Builds a printable calculation report (use the browser's "Save as PDF").
import { calculateNetwork, elementLabel } from '../core/impedance.js';
import { calculateQuick } from '../core/iecQuick.js';
import { BRAND } from '../config.js';
import { fmt, mOhm, esc } from './dom.js';

function pathTable(title, r) {
  if (!r) return '';
  return `<h4>${title}</h4><table><tr><th>Element</th><th>R (mΩ)</th><th>X (mΩ)</th></tr>
    ${r.path.map((p) => `<tr><td>${esc(p.label)}</td><td>${p.note ? '' : mOhm(p.R)}</td><td>${p.note ? '' : mOhm(p.X)}</td></tr>`).join('')}
    <tr><td><b>Total × ${fmt(r.tempFactor, 4)} (temperature)</b></td><td><b>${mOhm(r.Rt)}</b></td><td><b>${mOhm(r.Xt)}</b></td></tr></table>
    <p>Z' = ${mOhm(r.Z)} mΩ; Isc = ${fmt(r.Isc, 3)} kA; R/X = ${fmt(r.RX, 3)}; k = ${fmt(r.k, 3)}; I'sc = ${fmt(r.Ipeak, 3)} kA</p>`;
}

export function buildReport(p) {
  const net = calculateNetwork(p.network);
  const quick = calculateQuick(p.quick);
  const n = p.network;
  const list = (title, items) => (items.length ? `<h4>${title}</h4><ol>${items.map((e) => `<li>${esc(elementLabel(e))}</li>`).join('')}</ol>` : '');

  return `
  <header class="r-head"><div><h1>Short Circuit Calculation Report</h1>
    <div>${esc(BRAND.company)}</div></div>
    <table class="r-meta"><tr><td>Project</td><td>${esc(p.name)}</td></tr><tr><td>Client</td><td>${esc(p.client)}</td></tr>
    <tr><td>Ref.</td><td>${esc(p.ref)}</td></tr><tr><td>Engineer</td><td>${esc(p.engineer)}</td></tr>
    <tr><td>Date</td><td>${new Date().toLocaleDateString()}</td></tr></table></header>

  <h2>1. Impedance method</h2>
  <p>Method: impedance summation per phase; R and X corrected by 1 + α(T − 30) with T = ${n.settings.ambientTemp} °C, α = ${n.settings.alpha};
     Isc = V / (√3·Z'); k = 1.02 + 0.98·e^(−3R/X); I'sc = √2·k·Isc. Cable data from BS 7671 mV/A/m tables.</p>
  ${n.transformer.enabled ? `<p><b>Transformer source:</b> network ${n.transformer.networkMVA} MVA at ${n.transformer.hvVolts} V; transformer ${n.transformer.kva} kVA, Uk ${n.transformer.uk} %, ${n.transformer.lvVolts} V.</p>` : ''}
  ${n.generator.enabled ? `<p><b>Generator source:</b> ${n.generator.count} × ${n.generator.mva} MVA, ${n.generator.volts} V, X"d ${n.generator.xd} %.</p>` : ''}
  ${list('Transformer branch', n.transformer.enabled ? n.transformerBranch : [])}
  ${list('Generator branch', n.generator.enabled ? n.generatorBranch : [])}
  ${list('Common path', n.chain)}
  ${net.ok ? `
    <h3>Summary</h3>
    <table><tr><th>Point</th><th>V</th><th>Isc from Tr. (kA)</th><th>Isc from Gen. (kA)</th><th>Motors (kA)</th><th>Design Isc (kA)</th><th>Design peak (kA)</th><th>Min. Icu (kA)</th></tr>
    ${net.points.map((x) => `<tr><td>${esc(x.name)}</td><td>${x.V}</td><td>${x.fromTransformer ? fmt(x.fromTransformer.Isc, 2) : '-'}</td>
      <td>${x.fromGenerator ? fmt(x.fromGenerator.Isc, 2) : '-'}</td><td>${x.motors ? fmt(x.motors.Im, 2) : '-'}</td>
      <td><b>${fmt(x.design.Isc, 2)}</b></td><td><b>${fmt(x.design.Ipeak, 2)}</b></td><td>${x.breaker ? x.breaker.icu : '>150'}</td></tr>`).join('')}</table>
    ${net.warnings.map((w) => `<p class="r-warn">⚠ ${esc(w)}</p>`).join('')}
    <h3>Detailed working</h3>
    ${net.points.map((x) => `<section class="r-point"><h3>${esc(x.name)}</h3>
      ${pathTable('From transformer', x.fromTransformer)}${pathTable('From generator', x.fromGenerator)}
      ${x.motors ? `<p>Motor contribution: ${fmt(x.motors.Im, 3)} kA (peak ${fmt(x.motors.Ipeak, 3)} kA)</p>` : ''}</section>`).join('')}
  ` : `<p class="r-warn">Network inputs incomplete: ${net.errors.map(esc).join('; ')}</p>`}

  <h2>2. IEC 60909 simplified method</h2>
  ${quick.ok ? `<p>c = ${p.quick.c}; S"kq = ${p.quick.skq} MVA</p>
    <table><tr><th>Source</th><th>Qty</th><th>kV</th><th>I"k (kA)</th></tr>
    ${[...quick.items.t, ...quick.items.g, ...quick.items.m].filter((x) => x.qty > 0).map((x) => `<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${x.v}</td><td>${fmt(x.ik, 3)}</td></tr>`).join('')}
    <tr><td colspan="3"><b>Total I"k</b></td><td><b>${fmt(quick.total, 3)}</b></td></tr></table>
    ${quick.warnings.map((w) => `<p class="r-warn">⚠ ${esc(w)}</p>`).join('')}` : `<p class="r-warn">${quick.errors.map(esc).join('; ')}</p>`}

  <p class="r-foot">${esc(BRAND.footerNote)} Generated by ${esc(BRAND.appName)}.</p>`;
}
